### ISSUE TITLE
Add image to README + link to examples in GitHub Website next to description

### ISSUE THREAD

**Issue by ngokevin** [mokargas/aframe-lensflare-component#2]
Looking to add to the Registry :)

**Comment by mokargas** [comment]
Added to build 1.0.2

**Comment by ngokevin** [comment]
Cool, you can also add the website link at 
<img width="1074" alt="screen shot 2017-03-29 at 6 00 27 pm" src="https://cloud.githubusercontent.com/assets/674727/24482933/a4d189b8-14a9-11e7-90e2-232c4efcf3c1.png">

**Comment by mokargas** [comment]
Ahh yes - should be good to go now @ngokevin
